### DISCUSSION TITLE
version lockstepping

### DISCUSSION THREAD

**Discussion by jhheider** [pkgxdev/brewkit#294] [Ideas]
some packages require (or nearly require) being in version lockstep with another package. the example we have today are all the `facebook` libraries, which release weekly, use calver, and constantly break compatibility.

perhaps something like:
```yaml
dependencies:
  github.com/facebookincubator/fizz: sync
  facebook.com/folly: sync
  facebook.com/wangle: sync
```

where `sync` could be `match`, `lock`, `version`, or `{{version}}`. it complicates the solver, but is a very specific class of per-version versioning that shouldn't be awful.
