### DISCUSSION TITLE
`- kill: $name` verb for scripts

### DISCUSSION THREAD

**Discussion by jhheider** [pkgxdev/brewkit#310] [Ideas]
Currently, to ensure killing a process (in a test, usually), we need the following:
```yaml
test:
  dependencies:
    linux:
      gitlab.com/procps-ng/procs: '*'
  env:
    darwin:
      KILL: killall
    linux:
      KILL: pkill -x
  script:
    - $KILL something || true
```
This feels a little bit like boilerplate. We should consider adding a `kill` script verb to replace all of the above with
```yaml
test:
  - kill: something
```
