### DISCUSSION TITLE
reusable snippet "hacks"

### DISCUSSION THREAD

**Discussion by jhheider** [pkgxdev/brewkit#322] [Ideas]
We tend to end up with a lot of the same hacks spread across package.yml files. A recent example is this:
```yaml
    # curve25519-dalek 4.1.2 introduces some odd simd issues on x86-64
    - run: sed -i
        -e 's/version = "4.1.2"/version = "4.1.1"/'
        -e 's/0a677b8922c94e01bdbb12126b0bc852f00447528dee1782229af9c720c3f348/e89b8c6a2e4b1f45971ad09761aafb85514a84744b67a95e32c3cc1352d1f65c/'
        Cargo.lock
      if: '>=2024.2.6'
```
this *should* be resolved when rust-lang.org=1.78.0 is released (1.77.0 was _just_ released). For now, we have this across 5 different packages. It would be nice to have a `hacks` directory, so we could do:
```yaml:
    - hack: rust-simd-below-1.78
```
to reference `${PKGX_PANTRY_PATH}/hacks/rust-simd-below-1.78.yml`. For _now_ I only envision mergable `build.script[]` steps, but it could certain be extended to include `build.env` objects, and _possibly_ `build.depedencies`, though that feels worse.

`test` key values could be supported as well.
