### ISSUE TITLE
level 1 folders gets removed in the SRCROOT directory

### ISSUE THREAD

**Issue by getneil** [pkgxdev/brewkit#11]
brewkit version `0.2.7`
tea version `0.24.3`

Assuming there is a `v0.0.4.tar.gz` file with the ff content:
```
build/index.html
build/styles/style.css
src/app.ts
deno.lock
deno.jsonc
import-map.json
```

when inside the pantry repo executing `tea -SE pkg build`,
after downloading the tgz package the extracted SRCROOT dir ie `src-v0.0.4` has the ff content:
```
index.html
styles/style.css
app.ts
```

**Comment by getneil** [comment]
at the moment package.yml looks like this:
```
distributable:
  url: https://s3.amazonaws.com/BUCKET/release/v{{version}}.tar.gz
  strip-components: 1

versions:
  - 0.0.4

provides:
  - bin/app

build:
  dependencies:
    deno.land: ^1.3
  script: |
    ls

test: |
  echo "hello world"

```
