### ISSUE TITLE
`versions:` should accept an array of valid version objects

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#149]
linux-headers is currently:
```yaml:
versions:
  # FIXME: source for _all_ mainline versions
  url: "https://cdn.kernel.org/pub/linux/kernel/v5.x/"
  match: /linux-\d+\.\d+\.\d+\.tar\.xz/
  strip:
    - /linux-/
    - /\.tar\.xz/
```

So, _one_ way to do it would be to allow multiple versions objects as an array:
```yaml
versions:
  - url: "https://cdn.kernel.org/pub/linux/kernel/v4.x/"
    match: /linux-\d+\.\d+\.\d+\.tar\.xz/
    strip:
      - /linux-/
      - /\.tar\.xz/
  - url: "https://cdn.kernel.org/pub/linux/kernel/v5.x/"
    match: /linux-\d+\.\d+\.\d+\.tar\.xz/
    strip:
      - /linux-/
      - /\.tar\.xz/
  - url: "https://cdn.kernel.org/pub/linux/kernel/v6.x/"
    match: /linux-\d+\.\d+\.\d+\.tar\.xz/
    strip:
      - /linux-/
      - /\.tar\.xz/
```

although a potentially better way borrows from GHA:

```yaml
versions:
  matrix:
    major: [2, 3, 4, 5, 6]
  url: "https://cdn.kernel.org/pub/linux/kernel/v{{matrix.major}}.x/"
  match: /linux-\d+\.\d+\.\d+\.tar\.xz/
  strip:
    - /linux-/
    - /\.tar\.xz/
```

Obviously, both would translate the same internally, requiring a loop when checking versions.
