### ISSUE TITLE
build script doesn't revalidate base `working-directory`.

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#168]
The following fails (go.dev-type):
```yaml
build:
  working-directory: src
  script:
    - make.bash
    - mkdir -p "{{prefix}}"
    - run: mv src "{{prefix}}"
      working-directory: $SRCROOT
```
with
```shell
+ unset OLDWD
+ OLDWD=/var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/1892f004/src
+ mkdir -p /var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/1892f004
+ cd /var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/1892f004
+ mv src /opt/go.dev/v1.21.0
+ cd /var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/1892f004/src
/var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/1892f004/xyz.tea.build.sh: line 53: cd: /var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/1892f004/src: No such file or directory
```

Makes sense, but an odd gotcha. Could be prevented with a `test -d $foo || mkdir -p $foo`, or similar.
