### ISSUE TITLE
`pkg build` fails in `fix-macho.rb` (can’t find gem bundler)

### ISSUE THREAD

**Issue by j1philli** [pkgxdev/brewkit#185]
this seems to be a packaging bug but please let me know otherwise
**Console output**
```
+ npm version 1.102.2 --allow-same-version
v1.102.2
+ npm install . --prefix=/Users/joshphillips/.pkgx/wip/hibiscus/v1.102.2 --install-links

up to date, audited 28 packages in 384ms

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
  wip/hibiscus
/Library/Ruby/Site/2.6.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem bundler (= 2.3.7) with executable bundle (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.6.0/rubygems.rb:245:in `bin_path'
	from /Library/Ruby/Site/2.6.0/bundler/rubygems_integration.rb:178:in `bin_path'
	from /Library/Ruby/Site/2.6.0/bundler/shared_helpers.rb:283:in `set_bundle_variables'
	from /Library/Ruby/Site/2.6.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
	from /Library/Ruby/Site/2.6.0/bundler/runtime.rb:20:in `setup'
	from /Library/Ruby/Site/2.6.0/bundler/inline.rb:71:in `block in gemfile'
	from /Library/Ruby/Site/2.6.0/bundler/settings.rb:131:in `temporary'
	from /Library/Ruby/Site/2.6.0/bundler/inline.rb:55:in `gemfile'
	from /Users/joshphillips/.pkgx/pkgx.sh/brewkit/v0.49.0/share/brewkit/fix-machos.rb:9:in `<main>'
error: Uncaught Error: failed to fix machos
  if (!success) throw new Error("failed to fix machos")
                      ^
    at file:///Users/joshphillips/.pkgx/pkgx.sh/brewkit/v0.49.0/libexec/fixup.ts:33:23
    at eventLoopTick (ext:core/01_core.js:183:11)
```
**Pantry package.yml**
```
distributable:
  url: https://github.com/supabase/cli/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: supabase/cli  # reads github tags but only tags of releases (this is usually what you want)

dependencies:
  nodejs.org: '>=18.3'

build:
  dependencies:
    npmjs.com: '*'
    nodejs.org: '>=18.3'
  script: |
    npm version {{version}} --allow-same-version
    npm install . --prefix={{prefix}} --install-links

provides:
  - bin/supabase

test:
  script:
    npx supabase --version
```
