### ISSUE TITLE
Different distributable URL for each platform

### ISSUE THREAD

**Issue by krzyzanowskim** [pkgxdev/brewkit#274]
Is there a way to set up different URLs for each platform (Darwin/Linux)?

something along the way:

```
distributable:
  darwin:
    url: https://github.com/pkgxdev/darwin/brewkit/archive/refs/tags/v{{ version }}.tar.gz
  linux:
    url: https://github.com/pkgxdev/linux/brewkit/archive/refs/tags/v{{ version }}.tar.gz
```
