### ISSUE TITLE
darwin doesn't like gcc's ... ar and ranlib, I believe

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#277]
Found this in `open-mpi.org`; if it's the proper fix for `squashfs-tools-ng` as well, then we should immortalize it in `brewkit`'s toolchain.

>

              darwin doesn't like gcc's ... ar and ranlib, I believe. try this:
```
  env:
    darwin:
      # FIXME: binutils ar/ranlib are broken on macOS?
      AR: /usr/bin/ar
      RANLIB: /usr/bin/ranlib
```

_Originally posted by @jhheider in https://github.com/pkgxdev/pantry/pull/4883#discussion_r1456482112_
