### ISSUE TITLE
top-level `test.fixture` keys don't support `extname/content`

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#291]
https://github.com/pkgxdev/pantry/pull/4993/commits/f53024fa6bb7e7e988c33453327f69abbdabf153

it seems like `fixture` should work the same at the top level (or be removed? except shared fixtures would suffer.) as it does in script steps.

related: it might be useful for top-level (and even step-level) fixtures to support a `name` key, and an array of objects. that'd allow for:
```yaml
test:
  fixture:
    - {
      - name: a
      - extname: py
      - content: print("fixture a")
      }
    - {
      - name: b
      - extname: py
      - content: print("fixture b")
      }
  script:
    - python $FIXTURE_a
    - python $FIXTURE_b
```
though we don't _need_ this (yet). but it does provide one possible way to get rid of fixtures/props in the git repo (by moving them into the yaml). if we did this, we might want to let `fixtures` and `props` be top-level keys, so they could be segregated to the bottom to prevent visual clutter.

thoughts and ideas.
