### ISSUE TITLE
need to sanitize `+brewing` from more locations

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#317]
things currently in the pantry (may be solved already):

.cmake files:
```yaml
    - run: sed -i
        -e "s:{{ pkgx.prefix }}:\$\{CMAKE_CURRENT_LIST_DIR\}/../../../../..:g"
        -e "s/\+brewing//g"
        abslTargets{,-release}.cmake
      working-directory: '{{prefix}}/lib/cmake/absl'
```

.pc files:
```yaml
    # FIXME: this is a hack; we need to fix fixup.ts
    - run: sed -i 's/\+brewing//g' *.pc
      working-directory: '{{prefix}}/lib/pkgconfig'
```

possible contender:
```yaml
    # the make file uses sed over the bindir, our +brewing messes that up.
    - TMP_PREFIX=$(mktemp -d)
```

.la files going in now for `graphviz.org` to solve:
```
/opt/gnu.org/sed/v4.9.0/bin/sed: can't read /opt/graphviz.org/v10.0.1+brewing/lib/libxdot.la: No such file or directory
```
