### ISSUE TITLE
make ignoring github pre-releases optional

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#327]
See: https://github.com/foundry-rs/foundry/releases

**Comment by isworking** [comment]
Or perhaps (for less breaking), make *including* pre-releases optional?

Something like this:
```yaml
versions:
    github: org/repo/releases
    strip: /v/
    prerelease: true # this
```
Or, maybe an additional `/pre-releases` option?
Like:
```yaml
versions:
    - github: org/repo/pre-releases
      strip: /v/
    # If they release any proper (stable) version, it'd match that as well.
    - github: org/repo/releases
      strip: /v/
```
