### ISSUE TITLE
GITHUB_TOKEN required?

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/brewkit#33]
If I try to `pkg build` without GITHUB_TOKEN set then I get this message:

```
tea: installed: ~/Tea/pantry.extra/tea.out/cli.github.com/v2.24.0
no oauth token
```

If I set the GITHUB_TOKEN I get this error:

```
{
  rsp: Response {
  body: ReadableStream { locked: true },
  bodyUsed: true,
  headers: Headers {
  "access-control-allow-origin": "*",
  "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLim...",
  "content-length": "83",
  "content-security-policy": "default-src 'none'",
  "content-type": "application/json; charset=utf-8",
  date: "Wed, 08 Mar 2023 18:52:38 GMT",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  server: "GitHub.com",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  vary: "Accept-Encoding, Accept, X-Requested-With",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-media-type": "github.v4; format=json",
  "x-github-request-id": "CCDC:3C37:3C3AEE7:7B87119:6408D976",
  "x-ratelimit-limit": "0",
  "x-ratelimit-remaining": "0",
  "x-ratelimit-reset": "1678305158",
  "x-ratelimit-resource": "graphql",
  "x-ratelimit-used": "0",
  "x-xss-protection": "0"
},
  ok: false,
  redirected: false,
  status: 401,
  statusText: "Unauthorized",
  url: "https://api.github.com/graphql"
},
  json: {
    message: "Bad credentials",
    documentation_url: "https://docs.github.com/graphql"
  }
}
error: Uncaught (in promise) Error
        throw new Error()
              ^
    at Object.getVersions (https://raw.githubusercontent.com/teaxyz/cli/v0.24.7/src/hooks/useGitHubAPI.ts:78:15)
    at async handleComplexVersions (https://raw.githubusercontent.com/teaxyz/cli/v0.24.7/src/hooks/usePantry.ts:339:20)
    at async Object.resolve (https://raw.githubusercontent.com/teaxyz/cli/v0.24.7/src/hooks/usePantry.ts:42:20)
    at async file:///opt/tea/tea.xyz/brewkit/v0.6.0/libexec/resolve.ts:23:15
```

This is the package yml file I'm trying to build (I haven't gotten very far yet).

```
distributable:
  url: https://github.com/apple-oss-distributions/libtelnet/archive/refs/tags/libtelnet-{{ version }}.tar.gz
  strip-components: 1

versions:
  github: user/repo/tags
  strip: /^libtelnet-/

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |
    echo hi
```
